name: playfair
description: A simple charting library for Flutter
version: 0.0.10
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter/tree/master/packages/playfair

dependencies:
  flutter:
    path: ../flutter

dev_dependencies:
  test: 0.12.6

environment:
  sdk: '>=1.12.0 <2.0.0'
