language: dart
sudo: false
dart:
  - stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
  - ./travis/setup.sh
script:
  - ./travis/test.sh
