name: updater
author: Flutter Authors <flutter-dev@googlegroups.com>
description: An autoupdater for Flutter
homepage: http://flutter.io
dependencies:
  path: ^1.3.0
  yaml: ^2.1.3

  # TODO(abarth): Updater should not depend on flutter
  flutter:
    path: ../flutter
  flx:
    path: ../flx

environment:
  sdk: '>=1.12.0 <2.0.0'
