name: flutter_sprites
description: A sprite toolkit built on top of Flutter
version: 0.0.15
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io
dependencies:
  box2d: '>=0.2.0 <0.3.0'
  flutter:
    path: ../flutter
